service: ec2-start-instance-lambda

frameworkVersion: '4'

org: inxspin
app: ec2-start-instance-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  timeout: 60
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ec2:DescribeInstances"
            - "ec2:StartInstances"
          Resource: "*"

functions:
  startInstance:
    handler: handler.startInstance
    # # Event Bridge
    # events:
    #   - schedule:
    #       rate: cron(0/2 * * * ? *) # Run every 2 minutes

plugins:
  - serverless-offline
